import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import { ViewTransitions } from 'next-view-transitions';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({ weight: '400', subsets: ['latin', 'cyrillic'], });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="uk" className="scroll-smooth">
        <body
          className={roboto.className }
        >
            {children}
          <Footer />
        </body>
      </html>
    </ViewTransitions>
  );
}
